### ISSUE TITLE
Incorrect dependency for 0.2.0

### ISSUE THREAD

**Issue by grawlinson** [chasinglogic/licensure#16]
https://github.com/chasinglogic/licensure/blob/37de9c4289acd6a99ebce16905c4904d8c20adc3/Cargo.toml#L20

It seems that this should be `1.0.0`, as cargo complains about it.

```sh
Updating crates.io index
error: failed to select a version for `serde`.
... required by package `licensure v0.2.0
versions that meet the requirements `^0.2.0` are: 0.2.1, 0.2.0

the package `licensure` depends on `serde`, with features: `derive` but `serde` does not have these features.

failed to select a version for `serde` which could resolve this conflict
```

**Comment by aminya** [comment]
I fixed this in https://github.com/chasinglogic/licensure/pull/14, but the pull request was closed

**Comment by chasinglogic** [comment]
I'm unable to reproduce this issue, `cargo install licensure` works for me and on a clean VM.
