### ISSUE TITLE
Tag release 0.3.0?

### ISSUE THREAD

**Issue by marques-work** [chasinglogic/licensure#23]
@chasinglogic sorry to bug you again - would you mind pushing a tag for `0.3.0`? It would make it easier to build at a specific ref in tools like docker or workflows that need named references (e.g., homebrew).

**Comment by chasinglogic** [comment]
Doh! I tagged locally but forgot to push the tag. Doing it now

**Comment by marques-work** [comment]
I do that all the time :)

**Comment by chasinglogic** [comment]
Done and the github release is now made as well: https://github.com/chasinglogic/licensure/releases
