### ISSUE TITLE
`check` mode for CI pipeline integration

### ISSUE THREAD

**Issue by MathisWellmann** [chasinglogic/licensure#29]
It would be cool to add a `--check` flag that would essentially operate like normal but instead of writing to the file (or outputting the code) it would only output whether the desired license header is included.
This could be super useful in a CI pipeline that could enforce that every newly added file complies with the configured `.licensure.yml` file.
What do you think?
I'd be willing to put in the effort if this idea resonates with you.

P.S.: Awesome tool generally. I stumbled across it while looking for a tool that would automate this tedious work and within 30m all was setup and configured for my project. Will definitely keep using it in all my repos

**Comment by chasinglogic** [comment]
I think this is a great idea!

**Comment by chasinglogic** [comment]
Would welcome a PR for sure. I'm about to go on holiday for two weeks but will look at this when I'm back.
