### ISSUE TITLE
make template fetching an optional feature

### ISSUE THREAD

**Issue by hcldan** [chasinglogic/licensure#42]
There seems to be a lot of deps behind the use of reqwest which is just to fetch a license template, I'm assuming if one is not provided.

If you are willing, I (or someone else, maybe) might take a look at trying to make this a feature so licensure can be smaller with less deps, if desired.

**Comment by chasinglogic** [comment]
I don't really like the complexity that this suggestion adds. That means I'd have to maintain and publish two releases and users would have yet another decision to make.

I doubt that the size difference would really matter at all to anyone.

If someone wants to find a different HTTP client library that's smaller that would be fine.

**Comment by chasinglogic** [comment]
I switched to ureq in 0.5.1 which dramatically reduced the dependency count but the binary size is basically the same.

**Comment by hcldan** [comment]
thank you!
